// Catálogo de ideas de regalo.
//
// Cada idea es un TIPO de regalo, no un producto concreto: así no caduca, no depende de una
// tienda y el usuario busca la versión que mejor le encaje. Campos:
//   precio     [mín, máx] en euros para una versión decente
//   plazo      'hoy' (digital, experiencia o tienda de barrio), 'dias' (envío 24–72 h),
//              'semana' (personalizado o hecho a mano)
//   tipo       'objeto' | 'consumible' | 'experiencia' | 'digital' | 'tiempo'
//   intereses  aficiones con las que encaja; vacío = encaja con cualquiera
//   edades     'nino' | 'joven' | 'adulto' | 'mayor'; ausente = todas menos niños
//   relaciones 'pareja' | 'familia' | 'amistad' | 'trabajo'; ausente = todas
//   categorias ids de CATEGORIAS donde aparece destacada
//   porque     por qué suele acertar (lo que se lee en la sección de la idea)
//   busqueda   texto para buscarla en cualquier tienda

export const INTERESES = {
  cocina: '🍳 Cocina',
  cafe: '☕ Café y té',
  bebidas: '🍷 Vino y cerveza',
  deporte: '🏃 Deporte',
  naturaleza: '🥾 Montaña y aire libre',
  viajes: '✈️ Viajes',
  lectura: '📚 Lectura',
  musica: '🎧 Música',
  cine: '🎬 Cine y series',
  juegos: '🎲 Juegos de mesa',
  videojuegos: '🎮 Videojuegos',
  tecnologia: '💻 Tecnología',
  plantas: '🌱 Plantas y jardín',
  manualidades: '🎨 Arte y manualidades',
  bienestar: '🧖 Autocuidado',
  mascotas: '🐶 Mascotas',
  moda: '👟 Moda',
  foto: '📷 Fotografía',
};

export const CATEGORIAS = [
  {
    id: 'lo-tiene-todo',
    emoji: '🦄',
    nombre: 'Lo tiene todo',
    lema: 'Nada de más trastos: cosas que se gastan, se viven o mejoran lo que ya usa.',
    color: 'violeta',
  },
  {
    id: 'ultima-hora',
    emoji: '⏰',
    nombre: 'Para ya mismo',
    lema: 'Se regala hoy o mañana y no parece improvisado.',
    color: 'rojo',
  },
  {
    id: 'mejora-diaria',
    emoji: '✨',
    nombre: 'La versión buena',
    lema: 'Lo que usa cada día, pero en la versión que nunca se compraría.',
    color: 'ambar',
  },
  {
    id: 'experiencias',
    emoji: '🎟️',
    nombre: 'Planes, no cosas',
    lema: 'Un recuerdo compartido dura más que cualquier objeto.',
    color: 'azul',
  },
  {
    id: 'con-historia',
    emoji: '💌',
    nombre: 'Que emocione',
    lema: 'Regalos con memoria: fotos, cartas, recuerdos vuestros.',
    color: 'rosa',
  },
  {
    id: 'su-obsesion',
    emoji: '🔥',
    nombre: 'Para su obsesión',
    lema: 'Tiene una afición y quieres estar a la altura.',
    color: 'naranja',
  },
  {
    id: 'poco-dinero',
    emoji: '🪙',
    nombre: 'Menos de 20 €',
    lema: 'Detalles baratos que se nota que están pensados.',
    color: 'verde',
  },
  {
    id: 'en-grupo',
    emoji: '🤝',
    nombre: 'Entre varios',
    lema: 'Juntar el dinero para algo que de verdad quiera.',
    color: 'turquesa',
  },
  {
    id: 'compromiso',
    emoji: '💼',
    nombre: 'Compromiso sin riesgo',
    lema: 'Compañeros, amigo invisible o casi desconocidos.',
    color: 'gris',
  },
];

export const IDEAS = [
  // — Lo tiene todo / consumibles —
  {
    id: 'cesta-producto-local',
    nombre: 'Lote de productos locales buenos',
    porque: 'Se come y desaparece: no ocupa sitio y casi nadie se compra el aceite o el queso caro para sí.',
    precio: [25, 70], plazo: 'dias', tipo: 'consumible',
    intereses: ['cocina', 'bebidas'], categorias: ['lo-tiene-todo', 'compromiso'],
    busqueda: 'lote gourmet productos locales',
  },
  {
    id: 'cafe-especialidad',
    nombre: 'Suscripción de café de especialidad',
    porque: 'Un paquete distinto cada mes: el regalo se repite y se estrena cada vez.',
    precio: [20, 60], plazo: 'hoy', tipo: 'consumible',
    intereses: ['cafe'], categorias: ['lo-tiene-todo', 'su-obsesion'],
    busqueda: 'suscripción café de especialidad',
  },
  {
    id: 'te-cata',
    nombre: 'Caja de tés para probar',
    porque: 'Variedad en poco espacio; ideal si ya tiene su té favorito y le gusta curiosear.',
    precio: [15, 35], plazo: 'dias', tipo: 'consumible',
    intereses: ['cafe', 'bienestar'], categorias: ['poco-dinero', 'compromiso'],
    busqueda: 'caja degustación tés',
  },
  {
    id: 'vino-cata',
    nombre: 'Botella especial con una nota tuya',
    porque: 'La botella se bebe; la nota (“para abrir cuando…”) es lo que se recuerda.',
    precio: [15, 50], plazo: 'hoy', tipo: 'consumible',
    intereses: ['bebidas'], edades: ['adulto', 'mayor'], categorias: ['ultima-hora', 'lo-tiene-todo'],
    busqueda: 'vino especial regalo',
  },
  {
    id: 'especias',
    nombre: 'Kit de especias o salsas del mundo',
    porque: 'A quien cocina le da juego durante meses y es difícil que ya lo tenga igual.',
    precio: [15, 40], plazo: 'dias', tipo: 'consumible',
    intereses: ['cocina'], categorias: ['poco-dinero', 'su-obsesion'],
    busqueda: 'kit especias del mundo',
  },
  {
    id: 'cosmetica-buena',
    nombre: 'Jabón, crema o aceite de los buenos',
    porque: 'Convierte un gesto diario en un pequeño lujo y se gasta: cero trastos.',
    precio: [15, 45], plazo: 'hoy', tipo: 'consumible',
    intereses: ['bienestar'], categorias: ['lo-tiene-todo', 'mejora-diaria', 'compromiso'],
    busqueda: 'jabón artesanal crema natural regalo',
  },
  {
    id: 'flores-suscripcion',
    nombre: 'Flores frescas unos meses',
    porque: 'Cada entrega vuelve a recordar quién las regaló.',
    precio: [30, 90], plazo: 'hoy', tipo: 'consumible',
    intereses: ['plantas'], relaciones: ['pareja', 'familia', 'amistad'],
    categorias: ['lo-tiene-todo', 'ultima-hora'],
    busqueda: 'suscripción flores a domicilio',
  },

  // — Mejora diaria —
  {
    id: 'calcetines-buenos',
    nombre: 'Calcetines de lana merino',
    porque: 'Suena aburrido y es de lo más agradecido: se usan cada semana y nadie se los compra.',
    precio: [15, 30], plazo: 'dias', tipo: 'objeto',
    intereses: ['naturaleza', 'deporte'], categorias: ['mejora-diaria', 'poco-dinero'],
    busqueda: 'calcetines lana merino',
  },
  {
    id: 'toalla-grande',
    nombre: 'Toalla de baño grande y gruesa',
    porque: 'Después de probar una “sábana de baño” las normales parecen servilletas.',
    precio: [25, 60], plazo: 'dias', tipo: 'objeto',
    intereses: ['bienestar'], edades: ['adulto', 'mayor'], categorias: ['mejora-diaria'],
    busqueda: 'toalla sábana de baño algodón gruesa',
  },
  {
    id: 'cuchillo-cocinero',
    nombre: 'Un buen cuchillo de cocinero',
    porque: 'Se usa a diario; si cocina con uno barato, notará la diferencia el primer día.',
    precio: [40, 120], plazo: 'dias', tipo: 'objeto',
    intereses: ['cocina'], edades: ['adulto', 'mayor'], categorias: ['mejora-diaria', 'su-obsesion'],
    busqueda: 'cuchillo cocinero acero calidad',
  },
  {
    id: 'botella-termo',
    nombre: 'Botella o termo que no gotea',
    porque: 'Se lleva a todas partes; una buena mantiene el café caliente toda la mañana.',
    precio: [20, 45], plazo: 'hoy', tipo: 'objeto',
    intereses: ['deporte', 'naturaleza', 'cafe', 'viajes'], edades: ['joven', 'adulto', 'mayor'],
    categorias: ['mejora-diaria', 'compromiso'],
    busqueda: 'termo acero inoxidable',
  },
  {
    id: 'auriculares',
    nombre: 'Auriculares con cancelación de ruido',
    porque: 'Cambian el transporte, la oficina y los viajes. Mejor si lo juntáis entre varios.',
    precio: [80, 350], plazo: 'dias', tipo: 'objeto',
    intereses: ['musica', 'viajes', 'tecnologia'], edades: ['joven', 'adulto'],
    categorias: ['mejora-diaria', 'en-grupo'],
    busqueda: 'auriculares cancelación de ruido',
  },
  {
    id: 'lector-ebook',
    nombre: 'Lector de libros electrónicos',
    porque: 'Para quien lee mucho y viaja: la biblioteca entera en el bolsillo.',
    precio: [100, 250], plazo: 'dias', tipo: 'objeto',
    intereses: ['lectura', 'viajes'], edades: ['joven', 'adulto', 'mayor'],
    categorias: ['en-grupo', 'su-obsesion'],
    busqueda: 'lector libros electrónicos',
  },
  {
    id: 'bateria-externa',
    nombre: 'Batería externa pequeña y rápida',
    porque: 'Útil para todo el mundo y difícil de fallar: siempre se acaba usando.',
    precio: [20, 50], plazo: 'hoy', tipo: 'objeto',
    intereses: ['tecnologia', 'viajes'], edades: ['joven', 'adulto'],
    categorias: ['compromiso', 'ultima-hora'],
    busqueda: 'batería externa carga rápida',
  },
  {
    id: 'manta-buena',
    nombre: 'Manta de sofá de las que dan pena soltar',
    porque: 'Se usa cada noche de sofá y series; es el regalo que “no sabía que necesitaba”.',
    precio: [30, 80], plazo: 'dias', tipo: 'objeto',
    intereses: ['cine', 'lectura', 'bienestar'], categorias: ['mejora-diaria'],
    busqueda: 'manta sofá suave gruesa',
  },
  {
    id: 'mochila-buena',
    nombre: 'Mochila o bolso de diario resistente',
    porque: 'Si la suya está gastada, la va a usar a diario durante años.',
    precio: [40, 120], plazo: 'dias', tipo: 'objeto',
    intereses: ['viajes', 'moda', 'tecnologia'], edades: ['joven', 'adulto'],
    categorias: ['mejora-diaria', 'en-grupo'],
    busqueda: 'mochila diaria resistente portátil',
  },

  // — Experiencias —
  {
    id: 'entradas-concierto',
    nombre: 'Entradas para ver a su grupo o artista',
    porque: 'Es un plan con fecha: la ilusión dura desde que lo abre hasta el concierto.',
    precio: [30, 120], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['musica'], edades: ['joven', 'adulto', 'mayor'],
    categorias: ['experiencias', 'su-obsesion', 'en-grupo'],
    busqueda: 'entradas conciertos',
  },
  {
    id: 'clase-cocina',
    nombre: 'Taller de cocina para dos',
    porque: 'Aprende algo, se lo pasa bien y, si vas con esa persona, es un recuerdo común.',
    precio: [40, 120], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['cocina'], edades: ['joven', 'adulto', 'mayor'], relaciones: ['pareja', 'familia', 'amistad'],
    categorias: ['experiencias', 'lo-tiene-todo'],
    busqueda: 'taller de cocina para dos',
  },
  {
    id: 'taller-ceramica',
    nombre: 'Taller de cerámica o de manualidades',
    porque: 'Una tarde con las manos ocupadas y algo hecho por uno mismo para llevarse.',
    precio: [30, 80], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['manualidades'], categorias: ['experiencias', 'su-obsesion'],
    busqueda: 'taller cerámica iniciación',
  },
  {
    id: 'cata-vinos',
    nombre: 'Cata de vinos, cervezas o quesos',
    porque: 'Se aprende, se comparte y no queda nada en un cajón.',
    precio: [25, 70], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['bebidas', 'cocina'], edades: ['adulto', 'mayor'],
    categorias: ['experiencias', 'lo-tiene-todo'],
    busqueda: 'cata de vinos experiencia',
  },
  {
    id: 'spa-masaje',
    nombre: 'Circuito de spa o masaje',
    porque: 'Casi nadie se regala tiempo para sí; por eso se agradece tanto.',
    precio: [35, 120], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['bienestar'], edades: ['adulto', 'mayor'],
    categorias: ['experiencias', 'lo-tiene-todo', 'ultima-hora', 'en-grupo'],
    busqueda: 'circuito spa masaje regalo',
  },
  {
    id: 'escape-room',
    nombre: 'Escape room con su grupo de amigos',
    porque: 'Plan de una hora que da para cenas y anécdotas durante meses.',
    precio: [60, 120], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['juegos', 'videojuegos', 'cine'], edades: ['joven', 'adulto'], relaciones: ['amistad', 'pareja', 'familia'],
    categorias: ['experiencias', 'en-grupo'],
    busqueda: 'escape room reserva',
  },
  {
    id: 'escapada',
    nombre: 'Escapada de una noche',
    porque: 'El regalo estrella en pareja: tiempo juntos sin rutina.',
    precio: [90, 300], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['viajes', 'naturaleza'], edades: ['adulto', 'mayor'], relaciones: ['pareja', 'familia'],
    categorias: ['experiencias', 'en-grupo'],
    busqueda: 'escapada fin de semana',
  },
  {
    id: 'ruta-guiada',
    nombre: 'Ruta guiada, kayak o barranquismo',
    porque: 'Para quien siempre dice “algún día hago eso”: le das la fecha.',
    precio: [30, 90], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['naturaleza', 'deporte', 'viajes'], edades: ['joven', 'adulto'],
    categorias: ['experiencias', 'su-obsesion'],
    busqueda: 'actividad aventura kayak ruta guiada',
  },
  {
    id: 'teatro-cine',
    nombre: 'Entradas de teatro, musical o cine de estreno',
    porque: 'Plan fácil, con fecha y para compartir.',
    precio: [15, 80], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['cine'], categorias: ['experiencias', 'ultima-hora'],
    busqueda: 'entradas teatro musical',
  },
  {
    id: 'clase-deporte',
    nombre: 'Bono de clases (escalada, yoga, pádel…)',
    porque: 'Le empuja a probar lo que tiene pendiente sin tener que pagar la matrícula.',
    precio: [30, 100], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['deporte', 'bienestar'], edades: ['joven', 'adulto'],
    categorias: ['experiencias', 'su-obsesion', 'lo-tiene-todo'],
    busqueda: 'bono clases escalada yoga',
  },

  // — Con historia —
  {
    id: 'album-fotos',
    nombre: 'Álbum de fotos impreso de un año o un viaje',
    porque: 'Las fotos viven en el móvil y nadie las mira. Impresas se vuelven a abrir durante años.',
    precio: [20, 60], plazo: 'semana', tipo: 'objeto',
    intereses: ['foto', 'viajes'], relaciones: ['pareja', 'familia', 'amistad'],
    categorias: ['con-historia'],
    busqueda: 'álbum fotos personalizado',
  },
  {
    id: 'carta-tarro',
    nombre: 'Tarro de notas o cartas “ábrelas cuando…”',
    porque: 'Cuesta poco dinero y mucho tiempo, y eso es justo lo que se nota.',
    precio: [0, 10], plazo: 'hoy', tipo: 'tiempo',
    intereses: [], relaciones: ['pareja', 'familia', 'amistad'],
    categorias: ['con-historia', 'poco-dinero', 'ultima-hora'],
    busqueda: 'tarro de cartas ábrelas cuando',
  },
  {
    id: 'libro-recetas-familia',
    nombre: 'Libro con las recetas de la familia',
    porque: 'Recoge lo que no está escrito en ningún sitio. Para abuelos es oro.',
    precio: [15, 40], plazo: 'semana', tipo: 'objeto',
    intereses: ['cocina'], relaciones: ['familia'],
    categorias: ['con-historia'],
    busqueda: 'libro de recetas personalizado imprimir',
  },
  {
    id: 'mapa-estrellas',
    nombre: 'Lámina del cielo o del mapa de un día vuestro',
    porque: 'Pone fecha y lugar a un momento importante (dónde os conocisteis, un nacimiento…).',
    precio: [20, 50], plazo: 'semana', tipo: 'objeto',
    intereses: ['viajes', 'manualidades'], relaciones: ['pareja', 'familia'],
    categorias: ['con-historia'],
    busqueda: 'lámina mapa estrellas fecha personalizada',
  },
  {
    id: 'video-mensajes',
    nombre: 'Vídeo con mensajes de sus amigos y familia',
    porque: 'Gratis y de lo que más emociona: se nota el esfuerzo de coordinar a todos.',
    precio: [0, 0], plazo: 'semana', tipo: 'tiempo',
    intereses: [], relaciones: ['pareja', 'familia', 'amistad'],
    categorias: ['con-historia', 'poco-dinero', 'en-grupo'],
    busqueda: 'montar vídeo sorpresa mensajes',
  },
  {
    id: 'vale-tiempo',
    nombre: 'Vales de tiempo (“una cena hecha por mí”, “cuido a los niños”)',
    porque: 'Para quien anda sin tiempo, liberarle una tarde vale más que cualquier cosa.',
    precio: [0, 15], plazo: 'hoy', tipo: 'tiempo',
    intereses: [], relaciones: ['pareja', 'familia', 'amistad'],
    categorias: ['con-historia', 'poco-dinero', 'ultima-hora'],
    busqueda: 'vales regalo imprimibles',
  },

  // — Su obsesión —
  {
    id: 'juego-mesa',
    nombre: 'Un juego de mesa que aún no tenga',
    porque: 'Es un regalo y un plan a la vez. Pregunta en la tienda por uno para su grupo.',
    precio: [20, 60], plazo: 'dias', tipo: 'objeto',
    intereses: ['juegos'], edades: ['nino', 'joven', 'adulto', 'mayor'],
    categorias: ['su-obsesion', 'compromiso'],
    busqueda: 'juego de mesa recomendado',
  },
  {
    id: 'kit-cultivo',
    nombre: 'Planta bonita o kit para cultivar setas o hierbas',
    porque: 'Algo vivo que cuidar; se ve crecer y recuerda quién lo dio.',
    precio: [15, 40], plazo: 'dias', tipo: 'objeto',
    intereses: ['plantas', 'cocina'], categorias: ['su-obsesion', 'poco-dinero'],
    busqueda: 'kit cultivo setas hierbas aromáticas',
  },
  {
    id: 'material-arte',
    nombre: 'Material de calidad para su afición artística',
    porque: 'Quien pinta o dibuja suele ahorrar en material; la versión buena se nota.',
    precio: [20, 80], plazo: 'dias', tipo: 'objeto',
    intereses: ['manualidades'], edades: ['nino', 'joven', 'adulto', 'mayor'],
    categorias: ['su-obsesion', 'mejora-diaria'],
    busqueda: 'acuarelas rotuladores calidad profesional',
  },
  {
    id: 'libro-autor',
    nombre: 'El último libro de su autor favorito (firmado si se puede)',
    porque: 'Aciertas seguro si miras antes qué ha leído; firmado, se convierte en recuerdo.',
    precio: [15, 30], plazo: 'hoy', tipo: 'objeto',
    intereses: ['lectura'], edades: ['nino', 'joven', 'adulto', 'mayor'],
    categorias: ['su-obsesion', 'poco-dinero', 'ultima-hora'],
    busqueda: 'novedades libros',
  },
  {
    id: 'vinilo',
    nombre: 'Vinilo de un disco que le marcó',
    porque: 'Aunque no tenga tocadiscos, se enmarca. Si lo tiene, mejor todavía.',
    precio: [25, 45], plazo: 'dias', tipo: 'objeto',
    intereses: ['musica'], edades: ['joven', 'adulto', 'mayor'],
    categorias: ['su-obsesion', 'con-historia'],
    busqueda: 'vinilo disco',
  },
  {
    id: 'accesorio-mascota',
    nombre: 'Retrato ilustrado de su mascota',
    porque: 'Quien tiene perro o gato lo trata como familia; esto le emociona siempre.',
    precio: [25, 70], plazo: 'semana', tipo: 'objeto',
    intereses: ['mascotas'], categorias: ['su-obsesion', 'con-historia'],
    busqueda: 'retrato ilustrado mascota personalizado',
  },
  {
    id: 'tarjeta-juego',
    nombre: 'Saldo para su tienda de videojuegos',
    porque: 'Nadie sabe qué juegos tiene: así elige y no hay riesgo de repetir.',
    precio: [15, 70], plazo: 'hoy', tipo: 'digital',
    intereses: ['videojuegos'], edades: ['nino', 'joven', 'adulto'],
    categorias: ['su-obsesion', 'ultima-hora'],
    busqueda: 'tarjeta regalo videojuegos',
  },
  {
    id: 'revelado-foto',
    nombre: 'Correa, carrete o impresión de sus mejores fotos',
    porque: 'A quien le gusta la fotografía casi nunca imprime su trabajo.',
    precio: [15, 50], plazo: 'dias', tipo: 'objeto',
    intereses: ['foto'], categorias: ['su-obsesion'],
    busqueda: 'impresión fotográfica fine art',
  },
  {
    id: 'zapatillas-cuidado',
    nombre: 'Kit de limpieza para sus zapatillas',
    porque: 'Para quien mima sus zapatillas: práctico, barato y muy específico.',
    precio: [15, 30], plazo: 'dias', tipo: 'consumible',
    intereses: ['moda', 'deporte'], edades: ['joven', 'adulto'],
    categorias: ['su-obsesion', 'poco-dinero'],
    busqueda: 'kit limpieza zapatillas',
  },

  // — Digitales y suscripciones —
  {
    id: 'suscripcion-streaming',
    nombre: 'Unos meses de su plataforma de música o series',
    porque: 'Si comparte cuenta o usa la versión gratis, lo va a notar cada día.',
    precio: [15, 60], plazo: 'hoy', tipo: 'digital',
    intereses: ['musica', 'cine'], edades: ['joven', 'adulto', 'mayor'],
    categorias: ['ultima-hora', 'lo-tiene-todo'],
    busqueda: 'tarjeta regalo suscripción música series',
  },
  {
    id: 'curso-online',
    nombre: 'Curso de algo que siempre quiso aprender',
    porque: 'Idiomas, guitarra, fotografía… le das el empujón que llevaba tiempo aplazando.',
    precio: [20, 120], plazo: 'hoy', tipo: 'digital',
    intereses: ['musica', 'foto', 'cocina', 'manualidades', 'tecnologia'], edades: ['joven', 'adulto', 'mayor'],
    categorias: ['ultima-hora', 'experiencias'],
    busqueda: 'curso online guitarra fotografía idiomas',
  },
  {
    id: 'audiolibros',
    nombre: 'Suscripción de audiolibros',
    porque: 'Para quien quiere leer y no encuentra el rato: se escucha en el coche o paseando.',
    precio: [10, 60], plazo: 'hoy', tipo: 'digital',
    intereses: ['lectura', 'deporte'], edades: ['joven', 'adulto', 'mayor'],
    categorias: ['ultima-hora', 'lo-tiene-todo'],
    busqueda: 'suscripción audiolibros regalo',
  },

  // — Niños —
  {
    id: 'construccion',
    nombre: 'Juego de construcción',
    porque: 'Juego largo y abierto: vale para muchas edades y se combina con lo que ya tiene.',
    precio: [20, 80], plazo: 'dias', tipo: 'objeto',
    intereses: ['juegos', 'manualidades', 'tecnologia'], edades: ['nino'],
    categorias: ['su-obsesion'],
    busqueda: 'juego construcción niños',
  },
  {
    id: 'experimentos',
    nombre: 'Kit de experimentos o de ciencia',
    porque: 'Una tarde entera de “¡mira lo que pasa!”, y aprende sin darse cuenta.',
    precio: [15, 40], plazo: 'dias', tipo: 'objeto',
    intereses: ['tecnologia', 'naturaleza', 'manualidades'], edades: ['nino'],
    categorias: ['su-obsesion', 'poco-dinero'],
    busqueda: 'kit experimentos ciencia niños',
  },
  {
    id: 'plan-nino',
    nombre: 'Una salida solo para él o ella',
    porque: 'Zoo, acuario, parque de atracciones… a los niños les llenan más los planes que los juguetes.',
    precio: [15, 60], plazo: 'hoy', tipo: 'experiencia',
    intereses: ['naturaleza', 'mascotas', 'deporte'], edades: ['nino'], relaciones: ['familia', 'amistad'],
    categorias: ['experiencias', 'ultima-hora'],
    busqueda: 'entradas zoo acuario parque niños',
  },
  {
    id: 'libro-infantil',
    nombre: 'Libro ilustrado o cómic para su edad',
    porque: 'Pide consejo en la librería por edad; es barato y lo va a releer mil veces.',
    precio: [10, 25], plazo: 'hoy', tipo: 'objeto',
    intereses: ['lectura', 'manualidades'], edades: ['nino'],
    categorias: ['poco-dinero', 'ultima-hora'],
    busqueda: 'libro ilustrado infantil recomendado',
  },

  // — Compromiso —
  {
    id: 'tarjeta-local',
    nombre: 'Tarjeta regalo de una tienda o restaurante que le guste',
    porque: 'No es frío si eliges tú el sitio: demuestra que sabes a dónde le gusta ir.',
    precio: [20, 80], plazo: 'hoy', tipo: 'digital',
    intereses: [], categorias: ['compromiso', 'ultima-hora', 'en-grupo'],
    busqueda: 'tarjeta regalo restaurante',
  },
  {
    id: 'chocolate-bueno',
    nombre: 'Chocolate de calidad o dulces típicos de tu tierra',
    porque: 'Casi nadie dice que no, se comparte en la oficina y no hay que acertar la talla.',
    precio: [8, 25], plazo: 'hoy', tipo: 'consumible',
    intereses: ['cocina', 'cafe'], categorias: ['compromiso', 'poco-dinero', 'ultima-hora'],
    busqueda: 'chocolate artesanal caja regalo',
  },
  {
    id: 'planta-oficina',
    nombre: 'Planta pequeña que no se muere',
    porque: 'Para la mesa del trabajo: alegra y casi no pide cuidados.',
    precio: [8, 25], plazo: 'hoy', tipo: 'objeto',
    intereses: ['plantas'], categorias: ['compromiso', 'poco-dinero', 'ultima-hora'],
    busqueda: 'planta interior fácil cuidado',
  },
];
